language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
install: npm install
script:
  - npm run lint
  - npm test
  - npm run codecov
  - npm run clean && npm run build
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    on_success: never
    on_failure: change
